---
apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: default
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJndXlzYWFyOCIsInBhc3N3b3JkIjoiNFJvY2tMZWU4IiwiYXV0aCI6IlozVjVjMkZoY2pnNk5GSnZZMnRNWldVNCJ9fX0=
type: kubernetes.io/dockerconfigjson
