apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: role-for-kaniko
rules:
    - apiGroups:
        - ''
      resources:
        - 'pods'
      verbs:
        - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: roleBinding-for-kaniko
subjects:
    - kind: ServiceAccount
      name: default
      namespace: default
roleRef:
    kind: Role
    name: role-for-kaniko
    apiGroup: rbac.authorization.k8s.io
