apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: producer
  namespace: argocd
spec:
  project: default
  destination:
    namespace: defualt
    server: https://kubernetes.default.svc
  source:
    chart: producer
    repoURL: https://guysaar8.github.io/kubernetes_project
    targetRevision: 1.0.6
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
