apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq
  namespace: argocd
spec:
  project: default
  destination:
    namespace: rabbit-mq
    server: https://kubernetes.default.svc
  source:
    chart: rabbitmq
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 8.24.12
    helm:
      values: |-
        metrics:
          enabled: true
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
