#!groovy
pipeline {

   agent {
    kubernetes {
      yamlFile './producer-app/builder.yaml'
    }
  }
  
	stages {

    stage('Kaniko Build & Push Image') {
      steps {
        container('kaniko') {
          script {
            sh '''
            /kaniko/executor --dockerfile `pwd`/producer-app/Dockerfile \
                             --context `pwd` \
                             --destination=guysaar8/producer:${BUILD_NUMBER}
            '''
          }
        }
      }
    }
      

   }   
}
