# Default values for consumer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
serviceAccount: create
image: guysaar8/consumer
imagetag: 1.0.12
service:
  type: NodePort
  port: 80
