# Default values for consumer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image: guysaar8/consumer
imagetag: 0.0.0
service:
  type: NodePort
  port: 80
